[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
  functions = "src/functions"
  external_node_modules = ["@prisma/client"]
  command = "npm run build"
  publish = "build"